### ISSUE TITLE
Button (for Login or Submit or Delete or Add)

### ISSUE THREAD

**Issue by Bigshmow** [ppgeyser/plant-parenthood#14] opened 2019-11-12 21:42 UTC
This button will take the user's answer values and compare them to our list of plants' values.  Once the matches are made they will be displayed on the 'Survey Results' page from closest match on down.

 - [x] button (presentation)
 <s> - [ ] matching logic </s>  | will inject logic to onClick as needed.

**Comment by Zuzanav** [comment] 2019-11-16 20:26
Duplicate of #9

**Comment by Zuzanav** [comment] 2019-11-16 20:28
Duplicate of #8

**Comment by jnieves14** [comment] 2019-11-16 20:29
Duplicate of #11

**Comment by Bigshmow** [comment] 2019-11-16 21:36
Duplicate of #37

**Closed** 2019-11-18 05:08 UTC
Labels: Add Plant, Dashboard, Login Page, Survey Page
