### ISSUE TITLE
Plant Display Cards

### ISSUE THREAD

**Issue by ppgeyser** [ppgeyser/plant-parenthood#4] opened 2019-11-10 18:36 UTC
These are the cards that will populate after completion of the survey. Each card should have the following props:

- [ ] plant image
- [ ] species
- [ ] watering info
- [ ] additional care info
- [ ] button to add plant to collection
- [ ] button to dismiss suggestion

Not sure if parent card container that will contain all of the results cards should be part of the component or not.

**Comment by jnieves14** [comment] 2019-11-16 20:44
Duplicate of #12 ish

**Comment by jnieves14** [comment] 2019-11-16 20:52
Current issue will include #22 Plant image component

**Closed** 2019-11-19 02:37 UTC
Labels: Dashboard, Plant Result Page
